### PR TITLE
Merge develop into release-next

### PR DESCRIPTION
**Pull request by RastislavTuranyi**

### CODE REVIEW

**Comment by sanghamitra-mukhopadhyay** [comment]
Hi @RastislavTuranyi this pull request has to be updated to reflect the solved issue #133

**Comment by RastislavTuranyi** [comment]
I'm sorry, but I don't understand what you want me to do. Should I summarise the text #133 and put it into the description of this PR? In the first place though, #133 has not been merged yet; shouldn't any changes wait until that is done?

**Comment by sanghamitra-mukhopadhyay** [comment]
@RastislavTuranyi , I am sorry for this confusion. This branch has a conflict to be resolved. I thought it is related with #133. Please resolve the conflict.

**Comment by sanghamitra-mukhopadhyay** [comment]
Hi Rastislav,
I have merged the pull request. Can you please check that the “release-next” is ready for the release 1.5.1 ?
Many Thanks,
Sanghamitra

**Pull request merged**
