### PR TITLE
Update headers

### PR DESCRIPTION
**Pull request by RastislavTuranyi**
Each python file inside MDANSE contains a header with basic copyright information. However, these have not been updated since ISIS has taken over the development. This has been remedied by replacing in each file the copyright line
`# @copyright Institut Laue Langevin 2013-now`
with
```
# @copyright Institut Laue Langevin 2013-2021
# @copyright ISIS Neutron and Muon Source, STFC, UKRI 2021-now
```

### CODE REVIEW

**Comment by sanghamitra-mukhopadhyay** [comment]
Please resolve the conflicts as mentioned above.

**Comment by eurydice76** [comment]
We should thé ill header part back to 2013 - now as I am back on the project

**Comment by RastislavTuranyi** [comment]
The conflicts have been resolved. @sanghamitra-mukhopadhyay, should I change the headers again as Eric suggested? I don't really know how copyright works.

**Comment by sanghamitra-mukhopadhyay** [comment]
Since Eric is contributing regularly, @RastislavTuranyi please edit the copyright statement as below:
Institut Laue Langevin 2013-now
ISIS Neutron and Muon Source, STFC, UKRI 2021-now

**Pull request merged**
