### PR TITLE
Remove ability to plot non-meaningful data

### LINKED ISSUE #24: BUG: Plotter1D uses strings where they should be floats
Firstly, either the yMin or the yMax value used by Plotter1D (line plotter) can in some circumstances end up being a string, which prevents it from being used in mathematical operations, throwing an error. This error makes autofit unfunctional (even when used manually), and prevents users from setting the bounds of axes in the `Axes Settings`.

Traceback:
```
/opt/mdanse/lib/python2.7/site-packages/MDANSE/GUI/Plugins/PlotterPlugin.py -- 278 -- on_plot -- Plotter.plot(data, self.selectedVar)
/opt/mdanse/lib/python2.7/site-packages/MDANSE/GUI/Plugins/Plotter1D.py -- 448 -- plot -- self.on_auto_fit()
/opt/mdanse/lib/python2.7/site-packages/MDANSE/GUI/Plugins/Plotter1D.py -- 333 -- on_auto_fit -- self.Ymax=  yMax + 0.05*(yMax-yMin)

TypeError: unsupported operand type(s) for -: 'numpy.string_' and 'float'
```

How to reproduce:
1. Convert a trajectory using the `Box Translated Trajectory` plugin
2. Open the resulting .nc file in 2D/3D Plotter
3. From variables select `description`
4. Select Plotter should be line
5. Plot in new window

Secondly, changing `Modulation` in the above graph results in the following error:
```
/opt/mdanse/lib/python2.7/site-packages/MDANSE/GUI/Plugins/Plotter1D.py -- 255 -- on_offset -- self.add_offset(AddFactor)
/opt/mdanse/lib/python2.7/site-packages/MDANSE/GUI/Plugins/Plotter1D.py -- 311 -- add_offset -- line.set_ydata( (idx+1)*offset +y  )

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('S32') dtype('S32') dtype('S32')
```

### PR DESCRIPTION
**Pull request by RastislavTuranyi**
**Description of work.**

Fixes #24 

Currently, it is possible to plot all variables in a NetCDF file, including those that have no use or even those that do not make sense, such as the description of the trajectory, or time against atomic mass. Several such variables have been prevented from being displayed in the list of variables. If anyone knows of other variables which should not be available for plotting, please let me know.

Furthermore, when data containing non-numeric values is attempted to be plotted, it now results in an error with a meaningful message without actually plotting the data.

**To test:**

1. Load an .nc file containing a trajectory into 2D/3D Plotter.
2. Observe that there are no variables titled 'description', 'step', or 'time' available for plotting.

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**.

### CODE REVIEW

**Comment by RastislavTuranyi** [comment]
Hi, can you please elaborate on how the crash occurred? I have successfully loaded all the files present in `MDANSE/Data/Jobs_reference_data`, which include both NetCDF trajectories and the results of analyses, without any problems. Even files that are not meant to be used with 2D/3D Plotter, such as .md or .py files, simply throw an error, after which I was able to continue using the software.

Thank you!

**Comment by sanghamitra-mukhopadhyay** [comment]
I could load the .nc file of the converted trajectories, but still the field "configuration" and "gradient"  are available for plotting and MDANSE crashes to try to plot this field with selected plotting options iso-surface or scaler field. 

MDANSE also crashes while trying to plot "velocities" as scalar field. 

The following field should be removed from plotting: 
- "box size" 
- "configuration"
- "gradients", 

Put the X axis label while plotting "kinetic energy" and "temperature" as either step or time.
The field "velocities" is a 3D parameter. It should be plotted separately, as velocities in the X, Y, Z directions in addition to surface plotting.

**Comment by sanghamitra-mukhopadhyay** [comment]
If velocities are plotted with respect to steps that is also fine, because we know the time information of each step. However, it would be better to have option to plot velocities with respect to time as well. Will you try to do that? 

It would be good to plot directional positions and velocities with respect to steps or time, i.e., position_x wrt to steps etc. I assume these data are there in the converted Netcdf file.

**Comment by eurydice76** [comment]
I added some code in the last commit to automatically filtering out non numeric numpy data. Like so, no need to hardcode the variables that should be thrown out which is not nice on a maintainability point of view. However, I keep this part of your code as it is I did not want to be too invasive.

**Review by eurydice76 — APPROVED** [review]

**Comment by RastislavTuranyi** [comment]
Eric, if this were just about removing the non-numeric data as it had been at the beginning, then your solution would be perfect. However, Sanghamitra has requested other variables to also not appear, which are all numeric and I don't think can be recognised by software as non-meaningful other than through hardcoding. I guess we could remove the plot of time against time by forbidding the plotting of all variables against themselves, but I have no other idea how e.g. `box_size` could be forbidden without affecting other 2D plots.

As for velocities, Sanghaitra, if you look at the size of the array that is plotted, you can see it plots every component of the velocity vector (x, y, and z) of each atom at each time-step. The velocities are not plotted with respect to anything, as can be seen from the empty 'Axis' column. I guess it might be easier for us to reach an understanding if we have a synchronous discussion, so we should discuss this in our meeting.
image

As for plotting position_x wrt to steps, it should be possible, but that's a completely new feature and outside the scope of this PR. Can you please open a new issue describing what you would like to be added? Thank you!

**Comment by eurydice76** [comment]
Sorry Rastislav, I have not read in deeply the earlier discussion )-: So yes, you had no other choice than hardcoding the variable names. Anyway, the filter I added is still useful as a first prefiltering step as any non numeric data should be discarded at loading stage.

**Comment by RastislavTuranyi** [comment]
@sanghamitra-mukhopadhyay, I have removed velocities as well, so now there should not be any variables available from plotting when an MMTK NetCDF trajectory is loaded. Therefore, this PR should be ready to be merged. For the improvements to make these variables useful to plot, I have created #58 as we discussed.

**Pull request merged**
