### PR TITLE
Added support for HDF5 format for output files

### PR DESCRIPTION
**Pull request by eurydice76**
Hi @RastislavTuranyi and @sanghamitra-mukhopadhyay , I implemented the HDF file format support for the output of the analysis. Rastislav, to make it work, could you will please set h5py as a new dependency on the build server. The way I implemented it allows to use both NetCDF and HDF file in the MDANSE plotter. Please review carefully and give me some feedback/suggestions/corrections.

### CODE REVIEW

**Comment by RastislavTuranyi** [comment]
I keep getting this error `Warning! ***HDF5 library version mismatched error***`. Have you experienced that?

**Comment by eurydice76** [comment]
No, I did not have this warning on ubuntu20.04. Apart from that, does it work ?

**Comment by RastislavTuranyi** [comment]
Well, the code seems ok, but I can't test it until I resolve this issue, not unless I want to risk `Data corruption or segmentation faults may occur if the application continues.`.

**Comment by eurydice76** [comment]
Unfortunately I can't help you

**Comment by eurydice76** [comment]
Maybe it can help https://github.com/h5py/h5py/issues/853

**Comment by RastislavTuranyi** [comment]
Thanks for looking for solutions, but no I thread I have seen so far has been helpful/relevant. For now, I added installation of h5py in the pipeline, and also enabled the deploy for windows so that I can check if the GitHub Windows runner also has issues like me.

**Comment by eurydice76** [comment]
OK, let's cross the fingers

**Comment by eurydice76** [comment]
Hi @RastislavTuranyi , could you solve the warning with h5py on your machine ?

**Comment by RastislavTuranyi** [comment]
I can get it to work in my own environment by using some files from conda, but I'm having issues with making it work with the executable generated by CD.

**Comment by RastislavTuranyi** [comment]
I had to rewrite the Windows CI/CD to use conda python instead of the GitHub runner python, but I succeeded in making it produce an executable that works. However, I have discovered that when `UnitTests/AllTests.py` is run from a conda environment (and not just on the windows CI, but also on my laptop; on the other hand, this does not happen when the virtual environment is from `venv`), it gets stuck on opening the trajectory inside the `TestConfigurator.setUP()` method, never succeeding but never failing either. Can you please check if this happens for you too?

**Comment by eurydice76** [comment]
I just tried on my mahcine with a conda environment and everything was OK

**Comment by eurydice76** [comment]
Yeap, if that solves the problem, go ahead. However, it would be interesting to find why this trajectory triggers such infinite loop.

**Comment by RastislavTuranyi** [comment]
I have found the issue! As can be seen from this log, [alog.log](https://github.com/ISISNeutronMuon/MDANSE/files/8799415/alog.log), the while loop as below never ends because the END line has a wrong amount of whitespace. Changing the if statement on line 73 into `if l[0].strip() == 'END': break` has fixed the issue. Should I directly push that into the ILL MMTK repo, open a PR on GitLab, or just deal with it inside the pipeline?

```
        while True:
            l = FortranLine(file.readline()[:-1], 'A4,6X,A2')
            if l[0] == 'END ': break
            set_name = _normalizeName(l[0])
            ljpar_set = AmberLJParameterSet(set_name, l[1])
            self.ljpar_sets[set_name] = ljpar_set
            self._readLJParameters(file, ljpar_set)
```

**Comment by eurydice76** [comment]
The best would be to correct this in the ILL MMTK repo. Do you have the right to push ?

**Comment by RastislavTuranyi** [comment]
Now that you mention it, I probably don't, given that I don't work on it, don't have an ILL user account, and don't have a gtilab account. It would probably be easier if you handled that, if that is ok?

**Comment by eurydice76** [comment]
I commited the changes on MMTK repo. Everything should be OK now.

**Comment by RastislavTuranyi** [comment]
It seemed that the all the tests were stuck in an infinite loop, so I cancelled the run. After checking the new commit in the ILL MMTK repo, I noticed that the new line, `if l[0].strip() == 'END ': break`, has a space in the string, `'END '` instead of `'END'`, which is breaking the trajectories since after calling the strip() method on the l[0] string, there are no spaces left.

**Comment by eurydice76** [comment]
I just corrected the bug on MMTK. Sorry for not having been more careful.

**Comment by eurydice76** [comment]
However, they are still problems with MMTK tests. I do not know what happened to these days which works perfectly so far

**Comment by RastislavTuranyi** [comment]
OK, the CI/CD is now functional and creates installers that work. I had to remove the caching of python, which has slowed the windows CI even further, and the created installer is also larger than it used to be, but at least it works.

@sanghamitra-mukhopadhyay, for testing, I have updated the building instructions for windows in [#8](https://github.com/ISISNeutronMuon/MDANSE/issues/8#issuecomment-916223070). The functioning Windows installer is in [this run](https://github.com/ISISNeutronMuon/MDANSE/actions/runs/2423547472). MacOS and Ubuntu installers are in [this run](https://github.com/ISISNeutronMuon/MDANSE/actions/runs/2386973849).

**Comment by eurydice76** [comment]
I think that we are now ready to merge.

**Review by RastislavTuranyi — APPROVED** [review]

**Review by sanghamitra-mukhopadhyay — APPROVED** [review]

**Comment by RastislavTuranyi** [comment]
Just for the record, I would like to mention here that I have now found the root cause of this issue; it is due to the simultaneous use of h5py and netCDF4. It seems that when these two packages are installed with pip, each of them is built with a different version of HDF5 C binaries, and python, for some reason, cannot keep the packages linked separately. Therefore, when one is imported, its HDF5 binaries are then used for it as well as for the one that is imported later.

**Pull request merged**
