### PR TITLE
Q Vector generator fix

### PR DESCRIPTION
**Pull request by MBartkowiakSTFC**
**Description of work**
The code surrounding the q-vector generation has turned out not to be as stable as the rest of MDANSE.

**Fixes**
1. Corrected the error checks around the individual lines of parameters. This prevents the GUI from crashing on invalid input.
2. Corrected the q-vector generation code in ApproximateDispersionQVectors and MillerIndicesQVectors. There were still problems there resulting from conversion from Python 2.

**To test**
Try typing in wrong parameters for different q-vector generators in the GUI.
Run Dynamic Incoherent Structure Factor calculations using ApproximateDispersionQVectors and MillerIndicesQVectors to check if it completes without errors.

### CODE REVIEW

**Comment by ChiCheng45** [comment]
I've added a commit to set the background color to the default. Some issues with dark scheme.

Before
image

After
image

**Comment by ChiCheng45** [comment]
Some crashes are still occurring here some I've found from my initial testing.

Setting the following q vector settings:
- CircularQVectors
  - Set axis_1 and axis_2 to the same values.
  - Set axis_1 or axis_2 to a zero vector.

- LinearQVectors
  - Set axis to a zero vector.

Also, the GUI doesn't update properly. When I misconfigure the q-vectors it changes purple, as expected, when I change to a different q-vector generation type e.g. from CircularQVectors to LinearQVectors it stays purple.

Crashes when I try to use ApproximateDispersionQVectors with the DFTB water trajectory.
Dynamic Incoherent Structure Factor calculation using MillerIndicesQVectors works fine.

**Comment by MBartkowiakSTFC** [comment]
Thanks for testing it in detail. I will remove the problems you listed here.

**Comment by ChiCheng45** [comment]
ApproximateDispersionQVectors and MillerIndicesQVectors seem to be working fine now. Everything seems to be working well.
 
 The only problem I've come across so far now is that when you set an invalid setting it still lets you run the calculation. It completes fine, I think it must use the default settings.
 
 
image

**Review by ChiCheng45 — APPROVED** [review]
Looks great thanks for sorting the issues out.

**Pull request merged**
