### PR TITLE
Fix broken tests

### PR DESCRIPTION
**Pull request by RastislavTuranyi**
In recent development, on multiple occasions changes to the code have been made without changing the tests, resulting in a number of broken tests that currently exist on `develop`. Namely,

- #39  changed the behaviour of CASTEP converter. The testing behaviour was fixed on this branch.
- #40 changed the behaviour of PDF without reflecting the changes in the tests. However, since the resulting code has a bug, the tests for this will be corrected in #59 together with the bugfix.
- #50 changed the behaviour of a multitude of trajectory converters, breaking the tests for DFTB, Forcite, CASTEP, DMol, and Discover converters. This has been partially solved by ignoring the 'temperature' and 'kinetic_energy' variables present in the reference files, but DFTB and Forcite tests remain broken because the new code is capable of reading velocities while the reference files do not contain velocities. Can you please advise on this, @eurydice76? Is it better to hardcode inside `BuildJobTests.py` that in the dftb and forcite tests the velocities would not be compared, or is it better to generate new reference files in some manner?

Edit: Thanks to Miguel, new trajectories have been added for testing DFTB and Forcite converters. Reference files have been generated from these using current version of MDANSE for use in testing.

Edit 2: The tests broken due to the change of the `output_files` parameter in trajectory converters to `output_file` in #60 has also been fixed by handling the KeyError arising in the tests.

### CODE REVIEW

**Comment by eurydice76** [comment]
First of all, please apologize me, I may be the culprit for some of the failing tests because I forgot to update the Tests. To come on your question, the best would be obviously to have DFTB and Forcite trajectories which contains velocities and gradients but to do so we have to generate ones. @gonzalezma could you generate new (short) trajectory for us in order that we can update our tests ? In the meantime we can hardcode in BuildJobTests in order to have a successful test suite.

**Comment by eurydice76** [comment]
For me everything is OK, you can merge

**Review by eurydice76 — COMMENTED** [review]
For me everything is OK. Just one question, why did you change the example trajectory for Forcite converter ? The old one used to work correctly so far.

**Comment by RastislavTuranyi** [comment]
I didn't give it much thought. Since Miguel generated a new trajectory for Forcite, I made that the default trajectory. I trusted that the trajectory was created for a reason (not just so that I would then ignore it), but indeed it seems that both trajectories have velocities but not forces, so both are equally useable for testing purposes. Should I revert to the old trajectory?

**Comment by eurydice76** [comment]
No keep the one you use. No problem. You can merge.

**Comment by RastislavTuranyi** [comment]
This should have fixed all the tests (except PDF), so it should be ready to be merged.

**Comment by eurydice76** [comment]
Great ! Thanks. By the way, would there be a way to speed up the build for windows (e.g. not installing Visual Studio each time). That would be great.

**Comment by RastislavTuranyi** [comment]
I have already implemented a caching mechanism, as described in the attached file. It succeeded in making the windows pipeline faster than the MacOS one when I implemented it in #20.  So far, it seems that the failed CI runs have not triggered the mechanism, so I will observe whether it still works correctly now that multiple branches are involved, and make adjustments if necessary.
[How Windows CI-CD works.txt](https://github.com/ISISNeutronMuon/MDANSE/files/8589706/How.Windows.CI-CD.works.txt)

**Pull request merged**
