### PR TITLE
Implement velocity reading in Gromacs converter via TRR files

### LINKED ISSUE #43: ENHANCEMENT: Implement TRR reading into Gromacs converter
Specific implementation of #27 for Gromacs converter.

Currently, MDANSE is able to convert only XTC files from Gromacs simulations. However, these files do not contain velocity data since they are highly compressed. A Gromacs file format which does contain this and other information is TRR, but it is not currently implemented in MDANSE. Given that multiple analyses require velocity data, it would be useful to remedy this. The C and cython files for TRR parsing already do exist within MDANSE, since they were taken from MDTraj code along with those for XTC parsing, so all that is required is to write code in python within the main codebase to wrap and utilise these classes as well as create a complimentary GUI.

### PR DESCRIPTION
**Pull request by RastislavTuranyi**
**Description of work.**

Resolves #43

As described in #27, it is important to read velocities directly from trajectories, but MDANSE is not capable of doing that for outputs of most MD simulation packages. In the case of Gromacs, that is because MDANSE can convert only XTC trajectories, which never contain velocities. Instead, Gromacs stores these in TRR files. The code for parsing of these files already exists in MDANSE, so all that was required was to expose this to users. This was done within the already existing GromacsConverter class; now it can be initiated with either an XTC or a TRR trajectory and MDANSE will use the appropriate parser. If a TRR trajectory is used, the presence of velocities and forces is automatically detected, after which the present variables are saved. Since the TRR reading was implemented within the already existing framework, the GUI was also changed only minimally; the header of the box for these input files was changed to indicate that both XTC and TRR trajectories can be used.

Concerning the existing parser code, unnecessary parts were removed in a similar way to how the XTC parser was trimmed when it was adapted from MDTraj to MDANSE. Further, a doubled import which was causing issues was removed, and an issue where a constant defined at the beginning of the module was forgotten was solved by redeclaring the variable in the method which uses it.

Lastly, .gitignore has been changed to exclude xtc.c and trr.c, files created during build from xtc and trr cython modules.

Tests have been created by comparing XTC and TRR files that describe the same trajectory. These trajectories have been copied from MDAnalysis repository, where they are also used for testing. To compare velocities, a .npy file containing the velocities in the form of a numpy array has been generated using MDAnalysis, and this array is then used as the standard against which the velocities read by MDANSE are compared.

**To test:**

1. Run the new test from its directory:
```
cd Tests/FunctionalTests/Jobs
python test_gromacs_trr.py
```
2. Open GUI and run Gromacs converter using the pairs of new files (these are adk_oplsaa.pdb and adk_oplsaa.trr, and corbotoxin.pdb and corbotoxin.trr)

---

#### Reviewer ####

Please comment on the following ([full description](http://developer.mantidproject.org/ReviewingAPullRequest.html)):

##### Code Review #####

- Is the code of an acceptable quality?
- Does the code conform to the [coding standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the changes appropriately?
- Are the release notes saved in a separate file, using Issue or PR number for file name and in the correct location?

##### Functional Tests #####

- Do changes function as described? Add comments below that describe the tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been added/updated?

Does everything look good? Mark the review as **Approve**.

### CODE REVIEW

**Comment by RastislavTuranyi** [comment]
@eurydice76, I have tried merging develop into this branch as well, and found out that it was when I placed `data["velocities"] = self._velocities` that caused the test to crash. When I left it as `self._universe.setVelocities(self._velocities)`, one of the tests failed, but at least everything executed to completion.

**Comment by RastislavTuranyi** [comment]
I have changed to griadient, i.e. `data["gradients"] = self._forces`, and have had no issues; I don't think that causes anything. However, when I replaced the snapshot as you described, I got this output:

```
(gromacs) C:\Users\username\Documents\MDANSE\MDANSE\Tests\FunctionalTests\Jobs>python test_gromacs_trr.py
Launching job in monoprocessor mode for trr
ERROR
Launching job in monoprocessor mode for trr

(gromacs) C:\Users\username\Documents\MDANSE\MDANSE\Tests\FunctionalTests\Jobs>
```

If this is what you are getting as well, then that is not the `TestGromacsCobrotoxin` failing, but `TestGromacsADK`. Specifically, it fails in test_core where it tries to convert an XTC trajectory which does not contain velocities or gradients. As such, I am not surprised it dies horribly.

 I think the best way to change initialize function is as follows:
```
    def initialize(self):
        '''
        Initialize the job.
        '''
        data_to_be_written = ["configuration", "time"]

        # Create XTC or TRR object depending on which kind of trajectory was loaded
        if self.configuration["xtc_file"]["filename"][-4:] == '.xtc':
            self._xdr_file = xtc.XTCTrajectoryFile(self.configuration["xtc_file"]["filename"], "r")
            self._xtc = True
        elif self.configuration["xtc_file"]["filename"][-4:] == '.trr':
            self._xdr_file = trr.TRRTrajectoryFile(self.configuration["xtc_file"]["filename"], "r")
            self._xtc = False

            # Extract information about whether velocities and forces are present in the TRR file
            try:
                self._read_velocities = self._xdr_file.has_velocities
                self._read_forces = self._xdr_file.has_forces
            except AttributeError:
                self._read_velocities, self._read_forces = self._xdr_file._check_has_velocities_forces()
                if self._read_velocities < 0 or self._read_forces < 0:
                    raise RuntimeError("Could not determine whether velocities or forces are present!")

            # The TRRTrajectoryFile object returns ints for these values, so turn them into bools
            self._read_velocities, self._read_forces = bool(self._read_velocities), bool(self._read_forces)

            if self._read_velocities:
                data_to_be_written.append("velocities")
            if self._read_forces:
                data_to_be_written.append("gradients")
        else:
            raise GromacsConverterError('Invalid file format: Gromacs converter can only convert XTC and TRR files, '
                                        'but %s was provided.' % self.configuration["xtc_file"]["filename"][-4:])

        # The number of steps of the analysis.
        self.numberOfSteps = len(self._xdr_file)
        
        # Create all objects from the PDB file.  
        conf = PDBConfiguration(self.configuration['pdb_file']['filename'])

        # Creates a collection of all the chemical objects stored in the PDB file
        molecules = conf.createAll()
                                            
        # Create a universe and introduce dhe chemical objects found in the PDB file into the universe.
        self._universe = ParallelepipedicPeriodicUniverse()
        self._universe.addObject(molecules)

        # If a TRR trajectory is being read, initialise velocities and forces
        if not self._xtc:
            if self._read_velocities:
                self._universe.initializeVelocitiesToTemperature(0.)
                self._velocities = ParticleVector(self._universe)
            if self._read_forces:
                self._forces = ParticleVector(self._universe)

        # A MMTK trajectory is opened for writing.
        self._trajectory = Trajectory(self._universe, self.configuration['output_files']['files'][0], mode='w')

        # A frame generator is created.
        self._snapshot = SnapshotGenerator(self._universe, actions = [TrajectoryOutput(self._trajectory,
                                                                                       data_to_be_written, 0, None, 1)])
```

**Comment by eurydice76** [comment]
No, to test the behavior I describes you must save an analysis (mdanse --js gromacs) and set the cobrotoxin file instead of the default

**Comment by RastislavTuranyi** [comment]
Wait, do you have `self._universe.setVelocities(self._velocities)` or `data["velocities"] = self._velocities`? I had kept the former since earlier, but when I restore to the latter I get

```
Connected to pydev debugger (build 213.7172.26)

Process finished with exit code -1073741819 (0xC0000005)
```

**Comment by eurydice76** [comment]
ok so you also have troubles. For me it is a segfault. So something is broken in MMTK with the snapshot generator in case we are using data dictionary. The problem is that we have no other choice for passing the gradients.

**Comment by eurydice76** [comment]
Hi Rastislav, I found something very interesting if I replace:
self._velocities.array = velocities[0, :, :] by self._velocities.array = numpy.random.uniform(0,1,(self._universe.numberOfAtoms(),3))
and 
self._forces.array = forces[0, :, :] by self._forces.array = numpy.random.uniform(0,1,(self._universe.numberOfAtoms(),3))
it works ! So something might be fishy about the trr file loaded or about the trr files themselves.

**Comment by eurydice76** [comment]
I think I got it. The problem was that that the coords, velocities and forces read from the TRR file was a arrays of float32 whereas MMTK was expecting arrays of double (float64). This completely messed up the memory.

**Comment by eurydice76** [comment]
if you are OK I can merge

**Comment by RastislavTuranyi** [comment]
Oh, wow, I see, thank you for the help! If the tests are running, please go ahead and merge develop into this branch. I will then update the tests to include gradients if you haven't done that already.

**Comment by eurydice76** [comment]
I have completely messed up my repo by doing a rebase of the develop branch.

**Comment by RastislavTuranyi** [comment]
In that case I will push a merge commit while you get everything in order, and then you can test it. Is that acceptable?

**Comment by eurydice76** [comment]
the problem is that I did some changes to Src/Framework/Jobs/Gromacs.py file

**Comment by RastislavTuranyi** [comment]
I mean, you haven't pushed the changes, so in the worst case, you can delete your local repo and clone the remote, which would lose you all the work but also remove all the mistakes. This would allow me to make the changes instead, which you can adopt. 

There should be a better solution, but I am no git expert. Perhaps we can ask Franz if he can help?

**Comment by eurydice76** [comment]
ok, I will try a bit to make it through. If I can not make it, I come back to you

**Comment by eurydice76** [comment]
ok, I could make it. I do not know how :-) but it is OK. I run the test and merge if everything is OK

**Comment by RastislavTuranyi** [comment]
I have updated the tests and and cleaned up Gromacs.py. I also changed the `initialize()` method to the version I posted above so that the "velocities" and "gradients" are passed in dynamically based on whether they are present in the file or not, similar to how it is done in the other converters.

With that, I think this should be complete and stable, and should be available for merge. Usually I would now wait for @sanghamitra-mukhopadhyay to test it too and then merge it once she is satisfied everything is ok, so I'm not sure if we should merge this without her input. Still, if you are going to merge it as is, can you please do a squash merge? That's what we have been doing up till now to keep the history on develop clean.

**Comment by eurydice76** [comment]
I do not know what is a squash merge

**Comment by eurydice76** [comment]
OK I see what it is. Perhaps we can wait for @sanghamitra-mukhopadhyay review before you or I merge. If it is the way you proceed so far, i do not want to disrupt something that works.

**Comment by sanghamitra-mukhopadhyay** [comment]
Hi Rastislav,

It seems okay, however, I shall do further check in the evening and will do squash merge.

Many Thanks,
Best wishes,
Sanghamitra

**Review by eurydice76 — APPROVED** [review]

**Comment by eurydice76** [comment]
Hi @sanghamitra-mukhopadhyay, could you please review this code. Thanks

**Pull request merged**
