### PR TITLE
Fixed bug when closing line settings dialog

### PR DESCRIPTION
**Pull request by eurydice76**
See #178 for info

### CODE REVIEW

**Review by MBartkowiakSTFC — CHANGES_REQUESTED** [review]
@eurydice76 On my computer it was not a _complete_ success.
The line in the plot turned solid again after I closed Line Settings, as intended.
However, the entire GUI was blocked after I closed Line Settings (similar to when a modal dialog is open), so I could not do anything, and could not close MDANSE. All I get when I click on any MDANSE window is a 'ping' sound.
Was it OK on your computer?

**Comment by eurydice76** [comment]
@MBartkowiakSTFC I just retried on my ubuntu machine and its works perfectly. Very strange. It seems a new MaCOS specific problem. Could you please investigate on that ?

**Comment by MBartkowiakSTFC** [comment]
I am working on it. Thanks for confirming that it works fine on Ubuntu! I'll let you know once I have found a solution.

**Comment by MBartkowiakSTFC** [comment]
@eurydice76 I made it work on my computer with a minimal change, but since I know nothing about wxWidgets, please check if my 1-line commit makes sense.

**Comment by eurydice76** [comment]
Hi @MBartkowiakSTFC , your commit makes sense to me. I am a bit surprised that it is needed on MacOS and not on the other OS but it is OK for me. We can merge.

**Pull request merged**
