### PR TITLE
Text output in the plotter

### PR DESCRIPTION
**Pull request by MBartkowiakSTFC**
**Description of work**
To make it easier for the users to transfer their results to other software (e.g. for fitting), we add another view to the Plot Holder. It is a text viewer, which shows the analysis results as plain text.

**Fixes**
1. Improved the logger handling of exceptions and error messages.
2. Created DataWidget as an equivalent to PlotWidget.
3. Created Text as subclass of Plotter, to be used with DataWidget.

**To test**
Please load analysis results with 1D and 2D arrays (e.g. DOS and DISF). Make sure that they can be plotted.
Create a text output using the new button in plot selector.
"Plot" the results in the new tab. Check the following actions:
1. Changing the units of the axes.
5. Selecting/deselecting datasets.
6. Changing other plot properties in the dataset table on the left.
Plot properties should not affect the text output.

### CODE REVIEW

**Review by RobBuchananCompPhys — COMMENTED** [review]
Manual testing looks good, made the following suggestions.
For the text view holder
- CheckBox to display the text view as a "preview"
- SpinBox that allows for the precision of the data to be dynamically incremented/decremented
- ComboBox allowing user to change units of y-axis values
- Export button (i.e. text view to .csv)

For the Actions tabs
- Remove lattice QVectors since it is a base class and not intended for use

For the graphical plot holder
- Disable x and y offset sliders in the case of 1D Data plotting

@MBartkowiakSTFC

**Comment by MBartkowiakSTFC** [comment]
There are some improvements following the review:
1. The DataWidget in the plotter text view now has a number of controls for changing formatting. Also, the mode is "preview" by default, so large volumes of text do not appear unless explicitly requested,
2. There is a CSV output option in the DataWidget,
3. Error message handling in the GUI has been improved, and more errors are caught by the logger now instead of crashing the GUI,
4. Related to issue #530 if the sum of weights is 0, normalisation by the sum is **not applied**. This prevents the output files from being filled with NaN values. Now they will be filled with 0 instead.

**Comment by MBartkowiakSTFC** [comment]
@ChiCheng45 I prioritised this PR because it makes it easier for users to view and export the data from the GUI, which could be useful in the workshop tutorials. The stability improvements could be important for the same reason. Your opinion is welcome, especially since the tutorials were written almost exclusively by you.

**Comment by RobBuchananCompPhys** [comment]
I've done manual testing of the new features, they look good and are working well.
Just one suggestion made about simplifying the of the `enable_sliders()` method.

**Review by ChiCheng45 — COMMENTED** [review]
Looks good. Just a few things.

What are the differences between options in the save file?
image

Can we change the csv output so that there isn't a newline after each row? In excel there is a empty row between each row of data.
image

**Comment by MBartkowiakSTFC** [comment]
I added extra labels in the GUI to explain what the fields are for.
I made a change to the text output, which did not make a difference on my computer, but was intended to remove the extra lines on Windows. Did it work?

**Comment by ChiCheng45** [comment]
> I added extra labels in the GUI to explain what the fields are for. I made a change to the text output, which did not make a difference on my computer, but was intended to remove the extra lines on Windows. Did it work?

Thanks, that has sorted that out.

**Review by ChiCheng45 — APPROVED** [review]

**Pull request merged**
