### PR TITLE
Make Trajectory Viewer available without Molecular Viewer

### LINKED ISSUE #165: Make Trajectory Viewer independent of Molecular Viewer
Trajectory Viewer, #58, currently requires Molecular Viewer to be open be able to be started. However, this means that it cannot be started at all on MacOS 11 and 12 due to #148 and #158. Making this feature independent of Molecular Viewer would make it accessible on these platforms.

### PR DESCRIPTION
**Pull request by RastislavTuranyi**
**Description of work**

Resolves #165 

The Trajectory Viewer has been made available both with and without Molecular Viewer. This way, it can be accessed on systems where Molecular Viewer is broken while retaining the easy functionality it has had, i.e. to select atoms with Molecular Viewer for plotting in Trajectory Viewer.

**To test**

1. Open MDANSE GUI and load a trajectory
2. Go to Plugins>Miscellaneous _without_ opening the Molecular Viewer and open the Trajectory Viewer
3. Plot something and close Trajectory Viewer
4. Open Molecular Viewer
5. Open Trajectory Viewer and plot something

### CODE REVIEW

**Comment by eurydice76** [comment]
I pull the 165 branch and rebuild MDANSE but when repeating your protocol, the trajectory viewer is not proposed once the Trajectory is loaded

**Comment by RastislavTuranyi** [comment]
I'm sorry, but I don't understand what you mean by proposed. Are you saying that the Trajectory Viewer does not appear under the Miscellaneous section (as usual) without the Molecular Viewer being open (new), only when it is open (how it has been up until now)? Or that it does not appear at all, anywhere?

**Comment by eurydice76** [comment]
The trajectory viewer only appears when the molecular viewer plugin is the active one (old behavior).

**Comment by RastislavTuranyi** [comment]
I see, thank you for your clarification! That's quite weird though, I wonder what's the issue. I'll try using different systems for now to test the behaviour, and let you know if I figure something out.

**Comment by RastislavTuranyi** [comment]
This is really weird, the Trajectory Viewer appears without Molecular Viewer everywhere I try; my windows desktip, windows laptop, and ubuntu vm. @sanghamitra-mukhopadhyay, can you please try yourself as well?

image

**Comment by eurydice76** [comment]
Really strange. The branch containing that new feature is 165_make_trajectory_viewer_independent, isn't it ?

**Comment by RastislavTuranyi** [comment]
That's right. Let me run the CD to generate installers and we can check those.

**Comment by RastislavTuranyi** [comment]
Can you please try the generated installer? I tried the Windows and Ubuntu 22 ones, and it worked.

**Comment by eurydice76** [comment]
I am sorry but I do not know how to get the deb file.

**Comment by eurydice76** [comment]
Other thing that might be a problem, if you follow [that link](https://github.com/ISISNeutronMuon/MDANSE/actions/runs/3105991527/jobs/5032420175). You will be directed to the ubuntu 20.04 deploy section. However, in the details it is stated that the artefact are for ubuntu 21. Is that normal ?

**Comment by MBartkowiakSTFC** [comment]
> Other thing that might be a problem, if you follow [that link](https://github.com/ISISNeutronMuon/MDANSE/actions/runs/3105991527/jobs/5032420175). You will be directed to the ubuntu 20.04 deploy section. However, in the details it is stated that the deploy is for ubuntu 21. Is that normal ?

As far as I know, and based on what Rastislav told me, it is normal. That is, GitHub only provides Ubuntu LTS releases (18.04, 20.04, 22.04) as platforms for the Actions. So, the package for Ubuntu 21 is _built_ on Ubuntu 20.04. At the moment I am not sure how different the Ubuntu-21 build is from the Ubuntu-20.

**Comment by MBartkowiakSTFC** [comment]
> I am sorry but I do not know how to get the deb file. I always get lost when I dive into the github actions mess.

@eurydice76 I think that it should be here: https://github.com/ISISNeutronMuon/MDANSE/actions/runs/3105991527

**Comment by eurydice76** [comment]
thanks Maciej for the link, but I can't find any deb file to download from there

**Comment by eurydice76** [comment]
Forget what I just wrote, I could find them.

**Comment by eurydice76** [comment]
Hi @RastislavTuranyi , I confirm that with the deb file corresponding to the build of the 165_make_trajectory_viewer_independent branch, the behavior is OK i.e. the trajectory viewer appears when the trajectory is loaded without the molecular viewer. So, I do not know what is going on with my local build.

**Comment by RastislavTuranyi** [comment]
Well, that's good to hear! However, I don't think I can help you with your build, unfortunately; the only idea I have is to create a new virtual environment and install this branch there.

**Comment by eurydice76** [comment]
that what I just did and it is OK now. Strange but at least it works. Thanks

**Review by eurydice76 — COMMENTED** [review]
OK. Nothing to add.

**Pull request merged**
